import type { Language } from "@/lib/localization";

export type LocalizedProjectContent = {
  domain: string;
  summary: string;
  challenge: string;
  build: string;
  impact: string;
  outcome: string;
};

const baseProjects: Record<string, LocalizedProjectContent> = {
  "Smart Farming": { domain: "IoT Monitoring", summary: "Real-time sensor data platform for farmers using dashboards and SMS notifications.", challenge: "Field monitoring is difficult when data is scattered and decisions rely on delayed manual observation.", build: "Connected sensor inputs to a web dashboard and notification flow so farm conditions could be monitored more practically.", impact: "Bridged hardware and software to help field monitoring and decision making.", outcome: "Combined microcontroller data collection with a web dashboard for practical field visibility." },
  "MotioSuit": { domain: "Wearable Motion Capture", summary: "Low-cost motion capture suit project that reads IMU data in real time and sends it to Blender over Bluetooth.", challenge: "Motion capture work is usually expensive, so the challenge was building a more accessible pipeline with practical real-time feedback.", build: "Worked with IMU-based inputs, Bluetooth communication, and software-side integration concepts for live motion data workflows.", impact: "Shows the ability to work across sensors, hardware communication, and applied visualization workflows.", outcome: "Represents a strong hardware-plus-software direction for embedded and interactive systems." },
  "Auto RC Car": { domain: "Computer Vision Robotics", summary: "Autonomous RC car project using OpenCV and neural-network-driven processing in Python.", challenge: "Autonomous behavior requires perception, control flow, and reliable real-time response from a constrained physical platform.", build: "Used Python and OpenCV in an RC car workflow to connect vision processing with autonomous movement ideas.", impact: "Demonstrates applied AI and computer-vision work moving beyond dashboards into hardware behavior.", outcome: "Strengthened practical understanding of embedded autonomy, real-time pipelines, and model-driven interaction with the physical world." },
  "OCR": { domain: "Applied Computer Vision", summary: "Optical character recognition experiments using Python and OpenCV.", challenge: "Extracting readable text from images requires image preprocessing, recognition logic, and practical handling of imperfect visual inputs.", build: "Explored OCR-focused image processing workflows with Python and OpenCV to turn visual input into usable text output.", impact: "Shows practical work at the intersection of AI, image processing, and software utility.", outcome: "Expanded capability in computer vision pipelines and document or image understanding tasks." },
  "FetaMovies": { domain: "Consumer Web", summary: "Movie streaming experience built for registered users with a content-focused frontend.", challenge: "The goal was to deliver a simple consumer-facing browsing experience centered on media discovery and account access.", build: "Created a content-oriented web flow with authentication and structured movie browsing for registered users.", impact: "Delivered a consumer-facing web product with authentication and media browsing.", outcome: "Focused on a clean browsing flow and account-based access to entertainment content." },
  "Learning Management System": { domain: "Education Platform", summary: "Student registration, course management, and online testing in one system.", challenge: "Academic workflows often become fragmented across registration, learning, and assessment tools.", build: "Unified registration, course handling, and testing into a single platform with Django and AJAX-based interactions.", impact: "Centralized core academic workflows into a single learning platform.", outcome: "Reduced fragmented manual processes by bringing administration and assessments together." },
  "Python Car Game": { domain: "Interactive Software", summary: "Arcade-style car game built with Pygame.", challenge: "The focus was on strengthening event-driven logic, rendering feedback, and collision handling in a game loop.", build: "Implemented a lightweight driving game to practice state updates, player feedback, and frame-based interaction.", impact: "Strengthened game logic, rendering, and event-driven programming skills.", outcome: "Improved practical understanding of loops, animation, collision handling, and player feedback." },
  "Payroll System": { domain: "Business Operations", summary: "Business-focused payroll management system for salary and related processes.", challenge: "Payroll work is repetitive, error-prone, and operationally expensive when handled manually.", build: "Structured salary workflows and payroll-related records into a database-driven application for business operations.", impact: "Automated repetitive payroll workflows and business record handling.", outcome: "Turned salary management into a structured system with clearer operational control." },
  "Hospital Management": { domain: "Healthcare Systems", summary: "Full hospital workflow system for patients, appointments, and records.", challenge: "Healthcare operations require coordination across appointments, records, and administrative flows.", build: "Used a modern web stack to manage patient-facing and internal hospital workflows in one platform.", impact: "Supported core healthcare administration through a modern web stack.", outcome: "Improved how appointments, records, and patient flows could be managed in one place." },
  "Attendance System": { domain: "Workforce Tracking", summary: "Attendance tracking platform with reporting and dashboards.", challenge: "Administrators need simple visibility into attendance trends without relying on fragmented reporting.", build: "Created dashboards and reporting-oriented attendance workflows for easier monitoring and review.", impact: "Made attendance monitoring easier for administrators and staff.", outcome: "Delivered better visibility and reporting around staff presence and attendance history." },
  "HR System": { domain: "People Operations", summary: "Employee, leave, and performance management in one HR workflow.", challenge: "HR operations span multiple workflows that are hard to coordinate when managed in separate systems.", build: "Centralized employee, leave, and performance handling with a structured web-based workflow.", impact: "Improved visibility across HR operations with centralized data handling.", outcome: "Brought multiple HR processes into a single system instead of isolated manual steps." },
  "Bank Onboarding": { domain: "Digital Onboarding", summary: "Onboarding product spanning web, mobile, and USSD channels.", challenge: "Customer onboarding needs to serve both modern digital channels and constrained low-bandwidth environments.", build: "Extended onboarding flows across multiple delivery channels to broaden accessibility.", impact: "Expanded customer onboarding reach across digital and low-bandwidth channels.", outcome: "Supported broader customer access by covering both modern and constrained channels." },
  "Logistics System": { domain: "Operations Platform", summary: "Freight-style logistics platform for booking, tracking, and fleet management.", challenge: "Logistics operations become hard to manage when booking, tracking, and fleet coordination are spread across separate processes.", build: "Connected the operational workflow into one platform covering tracking, booking, and fleet visibility.", impact: "Connected multi-step logistics workflows into a single operational system.", outcome: "Made fragmented logistics workflows easier to track, coordinate, and manage centrally." },
};

export const projectContent: Record<Language, Record<string, LocalizedProjectContent>> = {
  en: baseProjects,
  am: {
    "Smart Farming": { domain: "IoT ክትትል", summary: "ለገበሬዎች በዳሽቦርድ እና SMS ማሳወቂያ የሚደገፍ የሴንሰር መረጃ ስርዓት።", challenge: "የእርሻ መረጃ ሲበተን እና ውሳኔ በዘገየ እይታ ሲመሰረት ክትትል ከባድ ይሆናል።", build: "የሴንሰር ግቤቶችን ከድር ዳሽቦርድ እና ማሳወቂያ ፍሰት ጋር አገናኘሁ።", impact: "ሀርድዌርና ሶፍትዌርን በማገናኘት ክትትልና ውሳኔ አሻሻለ።", outcome: "የmicrocontroller መረጃን ከድር ዳሽቦርድ ጋር በማጣመር ተግባራዊ እይታ ፈጠረ።" },
    "MotioSuit": { domain: "የእንቅስቃሴ መከታተያ", summary: "በአነስተኛ ወጪ የIMU መረጃን በእውነተኛ ጊዜ የሚልክ ፕሮጀክት።", challenge: "Motion capture ብዙ ጊዜ ውድ ስለሆነ ቀላል እና ተደራሽ ፍሰት ማቅረብ ዋና ግብ ነበር።", build: "IMU ግቤቶችን፣ Bluetooth ግንኙነትን እና የሶፍትዌር ግንኙነትን ላይ ተሰራ።", impact: "በsensor እና software visualization መካከል መስራት እንደምችል ያሳያል።", outcome: "ለembedded እና interactive systems ጠንካራ አቅጣጫ የሚያሳይ ስራ ነው።" },
    "Auto RC Car": { domain: "Computer vision ሮቦቲክስ", summary: "በOpenCV እና neural network የተመሰረተ የራስ ሰር RC car ፕሮጀክት።", challenge: "በተገደበ ሀርድዌር ላይ እውነተኛ ጊዜ እይታና ምላሽ ማቅረብ ከባድ ነው።", build: "Python እና OpenCV በመጠቀም የቪዥን ሂደትን ከራስ ሰር እንቅስቃሴ ጋር አገናኘሁ።", impact: "AI እና computer vision ወደ ሀርድዌር ባህሪ እንደሚሄድ ያሳያል።", outcome: "በembedded autonomy እና real-time pipelines ላይ ግንዛቤን አጠናክሯል።" },
    "OCR": { domain: "ተግባራዊ computer vision", summary: "በPython እና OpenCV የተሰሩ የፊደል ማወቂያ ሙከራዎች።", challenge: "ከምስሎች የሚነበብ ጽሑፍ ማውጣት የምስል አዘጋጅትና የማወቂያ ሂደት ይፈልጋል።", build: "OpenCV በተመሰረተ OCR ፍሰት በመሞከር ምስሎችን ወደ ጽሑፍ ቀየርሁ።", impact: "AI፣ image processing እና software utility መካከል ያለ ስራ ያሳያል።", outcome: "በdocument እና image understanding ላይ ክህሎቴን አሳደገ።" },
    "FetaMovies": { domain: "የድር መተግበሪያ", summary: "ለተመዘገቡ ተጠቃሚዎች የተገነባ የፊልም መመልከቻ ተሞክሮ።", challenge: "ቀላል የይዘት አሰሳና የመለያ መዳረሻ ያለው ተሞክሮ መፍጠር ነበር።", build: "ከauthentication ጋር የተደራጀ የፊልም አሰሳ ፍሰት ፈጠርሁ።", impact: "የconsumer web ፕሮዳክት በauthentication እና media browsing አቀረበ።", outcome: "ግልጽ የይዘት አሰሳ እና የመለያ መዳረሻ ተሞክሮ አቀረበ።" },
    "Learning Management System": { domain: "የትምህርት ፕላትፎርም", summary: "የተማሪ ምዝገባ፣ የኮርስ አስተዳደር እና ፈተና በአንድ ስርዓት።", challenge: "የትምህርት ፍሰቶች በብዙ መሳሪያዎች ሲበተኑ አስቸጋሪ ይሆናሉ።", build: "Django እና AJAX በመጠቀም ምዝገባን፣ ኮርስን እና ፈተናን አንድ ላይ አመጣሁ።", impact: "ዋና የአካዳሚክ ፍሰቶችን አንድ ስር አጠናቀቀ።", outcome: "fragmented manual processes በማስቀነስ ትምህርት አስተዳደርን አሻሻለ።" },
    "Python Car Game": { domain: "የተግባር ሶፍትዌር", summary: "በPygame የተሰራ የመኪና ጨዋታ።", challenge: "event-driven logic እና collision handling ላይ ልምምድ ማግኘት ነበር።", build: "ቀላል የመኪና ጨዋታ በመገንባት state updates እና player feedback ላይ ሰራሁ።", impact: "game logic እና rendering ክህሎቶችን አጠናክሯል።", outcome: "loops እና animation ላይ ተግባራዊ ግንዛቤ አሻሽሏል።" },
    "Payroll System": { domain: "የንግድ ስርዓት", summary: "ለደመወዝ አስተዳደር የተገነባ ስርዓት።", challenge: "payroll ስራ በእጅ ሲደረግ ተደጋጋሚ እና ስህተት የሚበዛበት ነው።", build: "salary workflows እና ተዛማጅ መረጃዎችን በdatabase-driven application ውስጥ አዋቀርሁ።", impact: "repetitive payroll workflows አውቶሜት አደረገ።", outcome: "salary management ወደ ግልጽ ስርዓት ቀየረ።" },
    "Hospital Management": { domain: "የጤና ስርዓቶች", summary: "ለታካሚዎች፣ ቀጠሮዎች እና መዝገቦች የሚያገለግል ሙሉ ስርዓት።", challenge: "የጤና ስራዎች በብዙ ፍሰቶች ሲሰሩ ማስተናገድ አስቸጋሪ ይሆናል።", build: "የታካሚና የውስጥ ስራ ፍሰቶችን በዘመናዊ የድር ስታክ አንድ ላይ አዋቀርሁ።", impact: "ዋና ዋና የጤና አስተዳደር ሂደቶችን ደገፈ።", outcome: "appointments እና records አንድ ላይ ለማስተዳደር የተሻለ ስርዓት ፈጠረ።" },
    "Attendance System": { domain: "የተገኝነት ክትትል", summary: "በሪፖርት እና ዳሽቦርድ የሚደገፍ የattendance ስርዓት።", challenge: "አስተዳዳሪዎች ቀላል የattendance እይታ ይፈልጋሉ።", build: "ዳሽቦርድና ሪፖርት ፍሰቶችን ፈጠርሁ።", impact: "attendance monitoring ቀላል አደረገ።", outcome: "የተገኝነት ታሪክ እና ሪፖርት ግልጽ አደረገ።" },
    "HR System": { domain: "የሰራተኞች አስተዳደር", summary: "employee, leave እና performance management በአንድ ፍሰት የሚያደርግ ስርዓት።", challenge: "HR ፍሰቶች በተለያዩ ስርዓቶች ሲኖሩ ማስተናገድ ከባድ ይሆናል።", build: "employee, leave እና performance ሂደቶችን በድር ስርዓት አንድ ላይ አመጣሁ።", impact: "HR እይታን በcentralized data handling አሻሽሏል።", outcome: "ብዙ የHR ሂደቶችን ከተበታተኑ እጅ ስራዎች ወደ አንድ ስርዓት አመጣ።" },
    "Bank Onboarding": { domain: "ዲጂታል ማስጀመሪያ", summary: "በweb፣ mobile እና USSD የሚሰራ የonboarding ፕሮዳክት።", challenge: "onboarding ለዘመናዊና ለlow-bandwidth channels አብሮ መስራት ይፈልጋል።", build: "onboarding flows በብዙ channels ላይ አራዘምኩ።", impact: "የደንበኛ መዳረሻን አስፋፋ።", outcome: "በmodern እና constrained channels ላይ የተሻለ መዳረሻ አቀረበ።" },
    "Logistics System": { domain: "የኦፕሬሽን ፕላትፎርም", summary: "ለbooking፣ tracking እና fleet management የተገነባ የlogistics ፕላትፎርም።", challenge: "logistics ሂደቶች በተለያዩ ፍሰቶች ሲኖሩ አስቸጋሪ ይሆናሉ።", build: "tracking፣ booking እና fleet visibility የሚያገናኝ ፕላትፎርም ፈጠርሁ።", impact: "multi-step logistics workflows አንድ ስር አገናኘ።", outcome: "ተበታተኑ ፍሰቶችን በቀላሉ ለመከታተልና ለማስተዳደር አስችሏል።" },
  },
  fr: {
    "Smart Farming": { domain: "Suivi IoT", summary: "Plateforme de capteurs en temps réel pour agriculteurs avec tableaux de bord et SMS.", challenge: "Le suivi du terrain devient difficile quand les données sont dispersées et observées trop tard.", build: "Connexion des capteurs à un tableau de bord web et à un flux de notification.", impact: "A relié matériel et logiciel pour améliorer le suivi et la décision.", outcome: "A combiné collecte microcontrôleur et tableau de bord pour plus de visibilité." },
    "MotioSuit": { domain: "Capture de mouvement", summary: "Projet de motion capture à faible coût envoyant les données IMU vers Blender par Bluetooth.", challenge: "La motion capture est souvent coûteuse; il fallait un pipeline plus accessible.", build: "Travail sur les entrées IMU, la communication Bluetooth et l’intégration logicielle.", impact: "Montre la capacité à travailler entre capteurs, matériel et visualisation.", outcome: "Représente une direction forte matériel + logiciel pour l’embarqué." },
    "Auto RC Car": { domain: "Robotique par vision", summary: "Projet de voiture RC autonome avec OpenCV et traitement neuronal en Python.", challenge: "Le comportement autonome demande perception, logique de contrôle et réponse temps réel.", build: "Python et OpenCV ont relié traitement visuel et mouvement autonome.", impact: "Démontre un travail appliqué en IA et vision sur matériel.", outcome: "A renforcé la compréhension de l’autonomie embarquée et des pipelines temps réel." },
    "OCR": { domain: "Vision appliquée", summary: "Expériences OCR avec Python et OpenCV.", challenge: "Extraire du texte depuis des images nécessite prétraitement et reconnaissance robustes.", build: "Exploration de workflows OCR pour transformer l’entrée visuelle en texte exploitable.", impact: "Montre un travail concret entre IA, image et utilité logicielle.", outcome: "A élargi les capacités en vision et compréhension de documents." },
    "FetaMovies": { domain: "Web grand public", summary: "Expérience de streaming vidéo pour utilisateurs enregistrés.", challenge: "Créer une expérience simple autour de la découverte de contenus et de l’accès compte.", build: "Création d’un flux web orienté contenu avec authentification.", impact: "A livré un produit web grand public avec navigation média.", outcome: "A proposé un flux clair de consultation et d’accès au compte." },
    "Learning Management System": { domain: "Plateforme éducative", summary: "Inscription étudiant, gestion des cours et tests en ligne dans un seul système.", challenge: "Les workflows académiques deviennent fragmentés entre inscription, apprentissage et évaluation.", build: "Unification des flux dans une plateforme Django avec AJAX.", impact: "A centralisé les workflows académiques de base.", outcome: "A réduit les processus manuels fragmentés." },
    "Python Car Game": { domain: "Logiciel interactif", summary: "Jeu de voiture type arcade développé avec Pygame.", challenge: "Le focus était sur la logique événementielle et les collisions.", build: "Implémentation d’un jeu léger pour pratiquer l’état et le feedback joueur.", impact: "A renforcé les compétences en logique de jeu.", outcome: "A amélioré la compréhension des boucles et collisions." },
    "Payroll System": { domain: "Opérations métier", summary: "Système de gestion de paie orienté métier.", challenge: "La paie manuelle est répétitive et propice aux erreurs.", build: "Structuration des flux de paie dans une application base de données.", impact: "A automatisé des workflows répétitifs.", outcome: "A transformé la paie en système structuré." },
    "Hospital Management": { domain: "Systèmes de santé", summary: "Système hospitalier complet pour patients, rendez-vous et dossiers.", challenge: "Les opérations hospitalières exigent une coordination continue.", build: "Gestion des workflows patients et internes dans une plateforme moderne.", impact: "A soutenu l’administration de santé.", outcome: "A amélioré la gestion unifiée des rendez-vous et dossiers." },
    "Attendance System": { domain: "Suivi de présence", summary: "Plateforme de suivi de présence avec reporting.", challenge: "Les administrateurs ont besoin d’une visibilité simple.", build: "Création de tableaux de bord et workflows de reporting.", impact: "A rendu le suivi plus simple.", outcome: "A offert une meilleure visibilité sur l’historique de présence." },
    "HR System": { domain: "Opérations RH", summary: "Gestion des employés, congés et performances dans un même workflow.", challenge: "Les opérations RH sont difficiles à coordonner dans des systèmes séparés.", build: "Centralisation des processus employés, congés et performance.", impact: "A amélioré la visibilité des opérations RH.", outcome: "A réuni plusieurs processus RH dans un seul système." },
    "Bank Onboarding": { domain: "Onboarding numérique", summary: "Produit d’onboarding couvrant web, mobile et USSD.", challenge: "L’onboarding doit fonctionner sur canaux modernes et faibles débits.", build: "Extension des flux sur plusieurs canaux.", impact: "A élargi la portée de l’onboarding client.", outcome: "A amélioré l’accès client sur plusieurs canaux." },
    "Logistics System": { domain: "Plateforme d’opérations", summary: "Plateforme logistique pour réservation, suivi et flotte.", challenge: "Les opérations logistiques se fragmentent quand les flux sont séparés.", build: "Connexion des flux de suivi, réservation et flotte dans une seule plateforme.", impact: "A relié les workflows logistiques multi-étapes.", outcome: "A facilité le suivi et la coordination centralisée." },
  },
  de: {
    "Smart Farming": { domain: "IoT-Überwachung", summary: "Echtzeit-Sensorplattform für Landwirte mit Dashboards und SMS.", challenge: "Feldüberwachung ist schwierig, wenn Daten verstreut sind und zu spät ankommen.", build: "Sensoren wurden mit Web-Dashboard und Benachrichtigungsfluss verbunden.", impact: "Verbindet Hardware und Software für bessere Überwachung.", outcome: "Kombiniert Datenerfassung und Dashboard für praktische Sichtbarkeit." },
    "MotioSuit": { domain: "Bewegungserfassung", summary: "Kostengünstiges Motion-Capture-Projekt mit IMU-Daten und Bluetooth.", challenge: "Motion Capture ist oft teuer; gefragt war ein zugänglicherer Workflow.", build: "Arbeit mit IMU-Eingaben, Bluetooth-Kommunikation und Software-Integration.", impact: "Zeigt Fähigkeit an der Schnittstelle von Sensorik, Hardware und Visualisierung.", outcome: "Stellt eine starke Hardware-und-Software-Richtung für Embedded-Systeme dar." },
    "Auto RC Car": { domain: "Computer-Vision-Robotik", summary: "Autonomes RC-Car-Projekt mit OpenCV und neuronaler Verarbeitung.", challenge: "Autonomes Verhalten verlangt Wahrnehmung, Steuerlogik und Echtzeitreaktion.", build: "Python und OpenCV verbanden Bildverarbeitung mit autonomer Bewegung.", impact: "Zeigt angewandte KI- und Vision-Arbeit auf Hardware.", outcome: "Vertiefte das Verständnis von Embedded-Autonomie und Echtzeit-Pipelines." },
    "OCR": { domain: "Angewandte Computer Vision", summary: "OCR-Experimente mit Python und OpenCV.", challenge: "Text aus Bildern zu extrahieren erfordert Vorverarbeitung und robuste Erkennung.", build: "OCR-Workflows wandelten visuelle Eingaben in nutzbaren Text um.", impact: "Zeigt praktische Arbeit zwischen KI, Bildverarbeitung und Software-Nutzen.", outcome: "Erweiterte Fähigkeiten in Vision-Pipelines und Dokumentverständnis." },
    "FetaMovies": { domain: "Consumer Web", summary: "Streaming-Erlebnis für registrierte Nutzer mit inhaltsorientiertem Frontend.", challenge: "Eine einfache Browsing-Erfahrung rund um Inhalte und Konto-Zugriff war das Ziel.", build: "Content-orientierter Web-Flow mit Authentifizierung und strukturierter Navigation.", impact: "Lieferte ein verbraucherorientiertes Webprodukt.", outcome: "Bot klaren Browsing-Flow und konto-basierten Zugriff." },
    "Learning Management System": { domain: "Bildungsplattform", summary: "Studentenregistrierung, Kursverwaltung und Online-Tests in einem System.", challenge: "Akademische Abläufe werden oft fragmentiert.", build: "Registrierung, Kurse und Tests in einer Django-Plattform vereint.", impact: "Zentralisierte akademische Kernprozesse.", outcome: "Reduzierte fragmentierte manuelle Abläufe." },
    "Python Car Game": { domain: "Interaktive Software", summary: "Arcade-artiges Autospiel mit Pygame.", challenge: "Der Fokus lag auf Event-Logik und Kollisionen.", build: "Leichtes Spiel zur Übung von Zustand und Spielerfeedback.", impact: "Stärkte Fähigkeiten in Spiellogik.", outcome: "Verbesserte das Verständnis von Schleifen und Kollisionen." },
    "Payroll System": { domain: "Geschäftsprozesse", summary: "Geschäftsorientiertes Lohnabrechnungssystem.", challenge: "Manuelle Gehaltsabrechnung ist repetitiv und fehleranfällig.", build: "Gehalts-Workflows in einer datenbankgestützten Anwendung strukturiert.", impact: "Automatisierte wiederkehrende Lohnprozesse.", outcome: "Verwandelte Gehaltsmanagement in ein strukturiertes System." },
    "Hospital Management": { domain: "Gesundheitssysteme", summary: "Krankenhaus-Workflow-System für Patienten, Termine und Akten.", challenge: "Gesundheitsabläufe erfordern Koordination über viele Prozesse hinweg.", build: "Patientennahe und interne Abläufe in einer modernen Plattform verwaltet.", impact: "Unterstützte zentrale Gesundheitsverwaltung.", outcome: "Verbesserte die gemeinsame Verwaltung von Terminen und Akten." },
    "Attendance System": { domain: "Anwesenheitsverfolgung", summary: "Plattform für Anwesenheit mit Reporting und Dashboards.", challenge: "Administratoren brauchen klare Sicht auf Anwesenheitstrends.", build: "Dashboards und Reporting-Workflows für einfacheres Monitoring erstellt.", impact: "Erleichterte die Anwesenheitsüberwachung.", outcome: "Verbesserte Sichtbarkeit auf Historie und Trends." },
    "HR System": { domain: "People Operations", summary: "Mitarbeiter-, Urlaubs- und Leistungsmanagement in einem Workflow.", challenge: "HR-Abläufe sind in getrennten Systemen schwer zu koordinieren.", build: "Mitarbeiter-, Urlaubs- und Performance-Prozesse zentralisiert.", impact: "Verbesserte Transparenz über HR-Abläufe.", outcome: "Vereinte mehrere HR-Prozesse in einem System." },
    "Bank Onboarding": { domain: "Digitales Onboarding", summary: "Onboarding-Produkt über Web-, Mobile- und USSD-Kanäle.", challenge: "Kunden-Onboarding muss moderne und bandbreitenarme Kanäle bedienen.", build: "Onboarding-Flows über mehrere Kanäle erweitert.", impact: "Erweiterte die Reichweite des Kunden-Onboardings.", outcome: "Verbesserte den Zugang über mehrere Kanäle." },
    "Logistics System": { domain: "Operations-Plattform", summary: "Logistikplattform für Buchung, Tracking und Flottenmanagement.", challenge: "Logistikprozesse werden schwer steuerbar, wenn Flows getrennt laufen.", build: "Tracking, Buchung und Flotten-Sichtbarkeit in einer Plattform verbunden.", impact: "Verknüpfte mehrstufige Logistik-Workflows.", outcome: "Erleichterte zentrales Nachverfolgen und Koordinieren." },
  },
};
